export * from './login.service';
export * from './usuario.service';
export * from './amigo.service';
export * from './convite.service';
export * from './jogo.service';
export * from './avaliacao.service';
export * from './estatistica.service';
export * from './erro.service';
export * from './mocks';
